### ISSUE TITLE
Rename `gen-datetime` to `datetime` for consistency

### ISSUE THREAD

**Issue by nberger** [gfredericks/test.chuck#19]
It seems like `com.gfredericks.test.chuck.generators/gen-datetime` is the only generator which has the `gen-` prefix.

Before closing a new release of test.chuck, it could be renamed to `com.gfredericks.test.chuck.generators/datetime`. We could also move the implementation details to a new `com.gfredericks.test.chuck.generators.datetime` namespace.

**Comment by gfredericks** [comment]
both sound fine to me

**Comment by nberger** [comment]
Cool, I'll do it soon

**Comment by gfredericks** [comment]
thanks for noticing the inconsistency
