### ISSUE TITLE
The test `exception-detection-test` is broken

### ISSUE THREAD

**Issue by nberger** [gfredericks/test.chuck#23]
It got broken on the last change (#21). I'm not sure what's wrong: if the library code or the test code. Anyways, it's something that needs to be fixed.

**Comment by gfredericks** [comment]
I swear I ran the tests before merging that but maybe I didn't?

**Comment by lackita** [comment]
I thought I ran the tests as well, I'll take a look tonight.

**Comment by nberger** [comment]
Maybe. Who knows :)

What do you think about integrating something like Travis or Circle? I have
it running in Circle in my fork, it just works given that new PR that sets
Xmx=1g

**Comment by gfredericks** [comment]
I've never set up CI for an OSS project before -- I don't know what the options are or how to do it, but I'm not opposed.

**Comment by gfredericks** [comment]
circleCI definitely thinks it's failing

**Comment by lackita** [comment]
Alright, fixed the issue in #25. It seems I was led down the garden path because the failing test was named this-test-should-crash. I renamed it to this-test-should-crash-and-be-caught to clarify that intention.

**Comment by nberger** [comment]
I also think it's fixed now.
