### ISSUE TITLE
`times` function not available in clojurescript

### ISSUE THREAD

**Issue by sandhu** [gfredericks/test.chuck#39]
The `times` function is not available in clojurescript. I'm happy to provide a PR to address that if there is no issue.

Thank you.

**Comment by gfredericks** [comment]
I think the whole point of the `times` function is that you can scale it via an env variable, which I assume doesn't apply in cljs (though maybe it does with node?); so for this to make sense we'd just need some form of configurability. I think even a dynamic var could help here (and could be useful in cljs as well), but maybe there's something specific to cljs as well?

**Comment by sandhu** [comment]
Even if it didn't support scaling in the cljs case, it would allow us to write unified test cases instead of having a conditional call to times in clj vs cljs.

I'll look into the configurability options in cljs and comment here.

**Comment by gfredericks** [comment]
yeah, I can see the portability advantages. If you want an earlier release that just makes it the identity function in cljs (and says so in the docstring), that sounds good to me.

**Comment by sandhu** [comment]
Sounds good. Will create a PR.
