### ISSUE TITLE
Shrunk case should be reported using pr-str

### ISSUE THREAD

**Issue by metametadata** [gfredericks/test.chuck#43]
First of all, great lib! 

I'd like to suggest wrapping shrunk case data into `(pr-str ...)` to make reports more readable. E.g. at the moment it would print vector of empty strings like this:

```
smallest case: [{v [  ]}]
```

but after wrapping into `pr-str` it would become:

```
smallest case: [{v ["" "" ""]}]
```

**Comment by gfredericks** [comment]
This happens when using the `com.gfredericks.test.chuck.clojure-test` namespace?

**Comment by metametadata** [comment]
Yes, when I use `checking` macro.

**Comment by gfredericks** [comment]
Okay, cool. I imagine adding a `pr-str` to the end of the threading form on [this line](https://github.com/gfredericks/test.chuck/blob/master/src/com/gfredericks/test/chuck/clojure_test.cljc#L24) would probably fix it.

**Comment by metametadata** [comment]
Yeah, it should.

**Comment by gfredericks** [comment]
This should be fixed by #44, and is released in `0.2.6`.
