### ISSUE TITLE
Unable to set `:seed` when using `checking`

### ISSUE THREAD

**Issue by bhb** [gfredericks/test.chuck#48]
If `checking` fails, it fails prints the message:

> Seed 1469058357988

However,  unlike [`defspec`](https://github.com/clojure/test.check/blob/3968dcf76be662813a62563084eaea34c51d4a2d/src/main/clojure/clojure/test/check/clojure_test.cljc#L40-L62), it isn't possible to pass the seed to `checking` to make it run the same series of tests.

Would you be interested in a PR that adds a version of `checking` that accepted a full set of [`quick-check` options](https://github.com/clojure/test.check/blob/3a3b1516112a5da887a6de94953e99f161cfcb1f/src/main/clojure/clojure/test/check.cljc#L46-L57)? That is, not only `:seed`, but also `:max-size` and `:reporter-fn`?

To preserve backwards compatibility, I think `checking` would need to have two forms. The old form would work as normal:

```clojure
(deftest a-failing-test
  (checking "all ints lt 5" 100
    [i gen/int]
    (is (< i 5))))
```
but the new form would replace the integer with a map for all options

```clojure
(deftest a-failing-test
  (checking "all ints lt 5" {:num-tests 100 :seed 1469058357988}
    [i gen/int]
    (is (< i 5))))
```

**Comment by gfredericks** [comment]
That sounds reasonable to me; that exact pattern is used in test.check itself somewhere I think

**Comment by nberger** [comment]
I could have used this a few weeks ago, so :+1:
