### ISSUE TITLE
README.md "More details in this blog post." link is broken

### ISSUE THREAD

**Issue by eereiter** [gfredericks/test.chuck#55]
The link to your blog has changed.  In your README.md file the link in your "this blog post." hyperlink goes to: http://blog.colinwilliams.name/blog/2015/01/26/alternative-clojure-dot-test-integration-with-test-dot-check/

But your blog post has been moved to:
http://blog.colinwilliams.name/clojure/testing/2015/01/26/alternative-clojure-dot-test-integration-with-test-dot-check.html

**Comment by gfredericks** [comment]
Fixed, thanks!
